[package]
name = "ide-assists"
version = "0.0.0"
repository.workspace = true
description = "Code assists for rust-analyzer."

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0"

itertools.workspace = true
either.workspace = true
smallvec.workspace = true
tracing = { workspace = true, features = ["attributes"] }
tempfile = "3.23.0"
verusfmt = { version = "0.5.5", default-features = false }

# local deps
stdx.workspace = true
syntax.workspace = true
ide-db.workspace = true
hir.workspace = true

[dev-dependencies]
expect-test = "1.5.1"

# local deps
test-fixture.workspace = true
test-utils.workspace = true

[features]
in-rust-tree = []
verus-integration-tests = []

[lints]
workspace = true
